apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: smf-example/smf-example
  name: smf-example
  namespace: oai-core
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|smf-example|smf-example'
spec:
  provider: smf.openairinterface.org
  parametersRefs:
  - name: oai-smf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
